### ISSUE TITLE
repo description

### ISSUE THREAD

**Issue by jayenashar** [sharetribe/web-template#276]
**Describe the bug** Repo description refers to older web templates that new visitors will not be familiar with

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'https://github.com/sharetribe/web-template'
3. Scroll down to 'About'
4. See Sharetribe Web Template - this combines the main features of older web templates'

**Expected behavior** A description that doesn't refer to the older web templates

**Desktop**

**Comment by Gnito** [comment]
Thanks! This is certainly a good point - especially, now that this repository has been the recommended starting point for half a year.
