### ISSUE TITLE
Bug in template subject

### ISSUE THREAD

**Issue by balynt2048** [sharetribe/web-template#407]
Hello,
I think the {transactionListingTitle} macro should be {listingTitle} here, as it is called everywhere in these templates and there is a mismatch between the placeholder and the value.

https://github.com/sharetribe/web-template/blob/25837d1555d49ff865b14ff1edf28bd734847509/ext/transaction-processes/default-purchase/templates/purchase-new-order/purchase-new-order-subject.txt#L1

**Comment by Gnito** [comment]
Hi, and thanks for reporting!

It seems that this has been fixed on default email templates on core side, but these reference email templates have not been updated at the time.

The fix was made to this direction: 

```
{{set-translations (asset "content/email-texts.json")}}{{t "PurchaseNewOrder.Subject" "{customerDisplayName} placed an order for {transactionListingTitle}" transactionListingTitle=transaction.listing.title customerDisplayName=transaction.customer.display-name }} 
```

I'll change this to that format tomorrow.

**Comment by Gnito** [comment]
Related PR: https://github.com/sharetribe/web-template/pull/413
