### ISSUE TITLE
Missing payout details banner not showing for 'purchase'

### ISSUE THREAD

**Issue by thibautlagarde** [sharetribe/web-template#442]
Hi Sharetribe,

I've probably found an issue in the codebase regarding the missing payout details banner displayed on Listing Pages.

Files:
`src/containers/ListingPage/ListingPageCoverPhoto.js` line 205
`src/containers/ListingPage/ListingPageCarousel.js` line 202

`const processType = isBooking ? ('booking' ? isPurchase : 'purchase') : 'inquiry';`
This caused the noPayoutDetails banner to never show for purchases.

I fixed it with this
`const processType = isBooking ? 'booking' : isPurchase ? 'purchase' : 'inquiry';`

Thanks!

**Comment by Gnito** [comment]
Thanks! It seems I haven't reviewed incoming changes properly.

**Comment by Gnito** [comment]
https://github.com/sharetribe/web-template/pull/443

**Comment by Gnito** [comment]
The suggested fix is now merged to the main branch. I'll close this issue.
